//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Answer()
        {
            this.PointAS = new HashSet<PointA>();
        }
    
        public int IDAnswer { get; set; }
        public string Content { get; set; }
        public bool Incognito { get; set; }
        public int IDAccount { get; set; }
        public int IDQuestion { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public bool Show { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Question Question { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PointA> PointAS { get; set; }
    }
}
