//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int ID { get; set; }
        public int IDAccount { get; set; }
        public int IDQuestion { get; set; }
        public bool Increase { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Question Question { get; set; }
    }
}
